### ISSUE TITLE
Github repo - "Not applicable- closed source"

### ISSUE THREAD

**Issue by stevieflow** [zararah/opendevtoolkit#7]
Two things

1 - People _can_ post open source code in places other than github?

2 - Is "Not applicable- closed source" the default answer when this is not completed?  For example, it the OIPA setup is available via a github repo via https://github.com/openaid-IATI but seems to be labelled as closed-source in the list.

**Comment by zararah** [comment]
Good points!
1. I've modified "Github" to say 'Source code' and the URL accordingly. 
1. "Not applicable" was the default answer, yes, but you're right- this is misleading! I've changed this now to say 'to be completed' as with the other fields.

Thank you!
